name: Build and Push Docker image 

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  run_script:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Log in to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    
    # Debug
    - name: Generate semver
      id: version-generator
      run: |
        ARTEFACT_VERSION=$(git describe --long --always | sed -r "s/-(([^-]*-){1}[^-]*)$/.\\1/")
        echo "ARTEFACT_VERSION=${ARTEFACT_VERSION}" >> $GITHUB_ENV
    
    # Debug   
    - name: Print ARTEFACT_VERSION
      run: echo "ARTEFACT_VERSION is $ARTEFACT_VERSION"


    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: |
          klimdos/nepromahbot:latest
          klimdos/nepromahbot:${{ env.ARTEFACT_VERSION }}
